import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

// Components
import Navbar from "@/component/layouts/navbar";
import Footer from "@/component/layouts/footer";
import "flowbite/dist/flowbite.min.css";

// Font
import { Roboto } from "next/font/google";
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "SEO", "Web Development"],
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://example.com",
    siteName: "Create Next App",
    images: [
      {
        url: "https://example.com/og-image.jpg",
        width: 800,
        height: 600,
        alt: "Og Image Alt",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@your_twitter_handle",
    creator: "@your_twitter_handle",
    title: "Create Next App",
    description: "Generated by create next app",
    images: ["https://example.com/twitter-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link
          href="https://fonts.gstatic.com"
          rel="preconnect"
          crossOrigin="anonymous"
        />
      </Head>
      <body className={roboto.className}>
        <Navbar></Navbar>
        <main>{children}</main>
        <Footer></Footer>
        <script
          src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"
          async
        ></script>
      </body>
    </html>
  );
}
